export * from "@prisma/client";
export * from "./audience.def"
export * from "./share.def"
export * from './gallery.def';
export * from './user.def';
export * from './like.def';
export * from './image.def';
export * from './post.def';
export * from "./chat.def";
export * from "./follow.def";
export * from './comment.def'
export * from "./feed.def"